

var arr = [[],[],[],[],[]]
arr[0].push(Math.floor(Math.random() * 25)+1)
var bingo = ['B','I','N','G','O']
console.log(arr);

var turnStatus = 0;
var boxesCount = 0;

var rndmStart =  Math.round(Math.random() * 1);


var lastPickedValue = 0;

// checking everytime if one of the elements inside this
// matrix equal to this specific rndm number i just generated
function isInside(arr, number){

    for(var i = 0; i <arr.length; i++){
        for(j=0; j< 5; j++){
            if (number == arr[i][j]){
                return true;
            }
        }
    }
    return false;
}

// add the rndm number to the empty arr
function addToArr(){
   
    for(var i =0; i < arr.length; i++){
        while(arr[i].length < 5){
            if(isInside(arr,number= Math.floor(Math.random() * 25)+1)){
                console.log('its already there');
            }else{
                arr[i].push(number);
            }
            
        }
    }
    
}

// keep calling the add function untill it fills the empty array
// where each rndm number needs to be checked if it's inside or not
// after comparing it with each element already inside the array
function keepAddingUntillFilled(){
for(var i =0; i < arr.length; i++){
    while(arr[i].length < 5){
        addToArr();
    }
    console.log(arr[i]);
}
console.log(arr);
}

arrColor=['#ffe0b2','#ffecb3','#ffe082','#ffcc80','#ffb74d',
        '#ffd180', '#ffab40','#ffd740','#ffe57f','#ffc400',
        '#f0f4c3','#f4ff81','#9e9e9e','#ef9a9a','#ff8a80',
        '#fbe9e7','#ffccbc','#ffab91','#ff8a65','#ff9e80',
        '#eceff1','#cfd8dc','#b0bec5','#bcaaa4','#a1887f']


// this function draws the matrix on the page based on the rndm numbers 
// inside the matrix generated by keepAddingUntillFilled function
function drawThatMatrix(arr){
    var thisRow = '<tr>';
    counter = 0;
    for(var i = 0; i < arr.length; i++){
        for(var j =0; j<arr[i].length;j++){
            thisRow += '<td style="background-color:'+arrColor[counter]+'";>' + arr[i][j] + '</td>';
            counter +=1;
        }
        thisRow += '</tr>';
        
        console.log(counter)
    }
    document.getElementById('player1').innerHTML = thisRow ;
}


// here every element i click on inside the page it changes that value to -1
// inside the array so i can track players progress and to check 
// the rows and columns and crosses
function changeToMinus(arr,value){
    for(var i = 0; i < arr.length;i++){
        for(var j =0; j<arr[i].length; j++){
            if(arr[i][j] == value){
                arr[i][j] = -1;
                return -1;
            }
        }
    }
}

// this function to count the rows
function countRow(arr){
    rowCount = 0;
    for(var i =0;i < arr.length;i++){
        var counter = 0;
        for(var j=0;j < arr[i].length;j++){
            if(arr[i][j] == -1){
                counter +=1;
            }
        }
        if(counter == 5){
            rowCount += 1;
        }
    }
    return rowCount;
}



function countColumn(arr){  // this function still not ready trying to think of a way
                            // to count the columns together @_@, oh god how stupid i am right now because im bad at math :(
                            // update: thanks to instructor SAAD now this function is ready.
    var colCount = 0;
    for(var i =0;i < arr.length;i++){
        var counter = 0;
        for(var j=0;j < arr[i].length;j++){
            if(arr[j][i] == -1){
                counter +=1;
            }
        }
        if(counter == 5){
            colCount += 1;
            counter = 0;
        }
    }
    return colCount;
}

function countCross(){ // this function counts Cross Columns
        var crossCount = 0;
        var counter = 0;
        for(var i =0;i < arr.length;i++){
            if(arr[i][i] == -1){
                counter += 1;
            }
            
            if(counter == 5){
                crossCount += 1;
            }
        }
        
        counter = 0;
        for(var i = arr.length-1, j=0; i >= 0; i--, j++){
            if(arr[j][i] == -1){
                counter += 1;
                console.log('anything',counter);
            }
            if (counter == 5){
                crossCount += 1;
            }
        }

        
    return crossCount;
}

function openCongratsPage1(){
    window.location = 'win1.html';
}
function winCondition(arr,bingo){
    numberOfRows = countRow(arr);
    console.log('number of rows',numberOfRows);
    numberOfColumns = countColumn(arr);
    console.log('number of columns',numberOfColumns);
    numberOfCross = countCross()
    sumOfColumnsRowsCross = numberOfRows + numberOfColumns + numberOfCross;
    for(var i=0;i < sumOfColumnsRowsCross; i++){ //this way does some duplications in the HTML Page
                                                 // i suggest you use array of ones and zeros to solve that 
        if(sumOfColumnsRowsCross < 5){
            bingo[i] = '<s>' + bingo[i] + '</s>';
        }else{
            openCongratsPage1();
            break;
        }
    }

    return bingo;
}

function startFromRNDMSart(){
    if(rndmStart == 1){
        console.log('rndmStart: ',rndmStart);
        turnStatus = 1;
        document.getElementsByClassName('tb2')[0].style.display = '';
        document.getElementsByClassName('tb1')[0].style.display = 'none';
    }else{
        console.log('rndmStart: ',rndmStart);
        turnStatus = 0;
        document.getElementsByClassName('tb1')[0].style.display = '';
        document.getElementsByClassName('tb2')[0].style.display = 'none';
    }
}


// hear i added an event listner to each box inside the table for the hover effect
// on MOUSEOVER and MOUSEOUT events so i can change thier effects
// 
function addTdListners(){
    var x = document.getElementsByTagName("td");
    console.log(x[0]);
    
    
    // z[0].addEventListener("mouseout", function(){ document.getElementsByClassName('tb2')[0].style.opacity = ''; });
    for(var i =0; i<x.length;i++){
        x[i].addEventListener("click", function(){
            
            x = changeToMinus(arr, this.innerHTML);
            lastPickedValue = this.innerHTML;
            if(Boolean(this.getAttribute("Picked"))){
                boxesCount-=1;
            }
            document.getElementsByClassName('lastPickedNumber')[0].innerHTML = lastPickedValue;
            // this.innerHTML = '<s>'+ this.innerHTML +'</s>';
            this.style.opacity = '0.2'
            this.setAttribute('Picked', true);
            console.log(arr,'im hereeeee'); 
            y = winCondition(arr,bingo);
            x = document.getElementById('bingo');
            for(var i =0; i < bingo.length; i++){
                x.innerHTML = y
            }
            
            if(boxesCount < 2 && turnStatus == 0){
                boxesCount+=1;
                if(boxesCount == 2){
                    turnStatus = 1;
                    document.getElementsByClassName('tb2')[0].style.display = '';
                    document.getElementsByClassName('tb1')[0].style.display = 'none';
                    boxesCount = 0;
                    lastPickedValue = 0
                }
            }
            document.getElementsByTagName('label')[0].innerHTML= ''
        });
        x[i].addEventListener("mouseover", function(){ this.style.backgroundColor = this.style.backgroundColor; this.style.boxShadow = '0px 0px 3px 2px black';this.style.borderRadius = '5px'});
        x[i].addEventListener("mouseout", function(){ this.style.backgroundColor = this.style.backgroundColor; this.style.boxShadow = ''; this.style.borderRadius = ''});
    }
}


keepAddingUntillFilled();

drawThatMatrix(arr);
addTdListners();
startFromRNDMSart();

